# Generated by Django 3.2.7 on 2022-08-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategorie',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('BIZNES', 'Biznes'), ('TECHNOLOGIE', 'Technologie'), ('POLITYKA', 'Polityka'), ('NAUKA PROGRAMOWANIA', 'Nauka Programowania'), ('NARZĘDZIA', 'Narzędzia'), ('INNE', 'Inne')], default='INNE', max_length=20),
        ),
    ]
