# Generated by Django 3.2.15 on 2022-09-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_kategorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria_nazwa', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.kategorie'),
        ),
    ]
