# Generated by Django 3.2.15 on 2022-09-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220907_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategorie',
            old_name='kategoria_nazwa',
            new_name='kategoria',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='kategorie',
            new_name='kategoria',
        ),
    ]
